config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'

  resources :courses, only: [:index, :show]

  namespace :instructor do
  	resources :sections, only: [] do
      resources :lessons, only: [:new, :create]
    end
  	resources :courses, only: [:new, :create, :show] do
  		resources :sections, only: [:new, :create] do
  			resources :lessons, only: [:new, :create]
  		end
  	end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	belongs_to :user
	has_many :sections

	validates :title, presence: true
	validates :description, presence: true
	validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}
end

app/models/lesson.rb
class Lesson < ApplicationRecord
	belongs_to :section
end

app/models/section.rb
class Section < ApplicationRecord
	belongs_to :course
	has_many :lessons
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :courses
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses = Course.all
	end

	def show
		@course = Course.find(params[:id])
	end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
	before_action :authenticate_user!

	def new
		@course = Course.new
	end

	def create
		@course = current_user.courses.create(course_params)
		if @course.valid?
			redirect_to instructor_course_path(@course)
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show
		@course = Course.find(params[:id])
	end

	private

	def course_params
		params.require(:course).permit(:title, :description, :cost)
	end
end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
	before_action :authenticate_user!
	before_action :require_authorized_for_current_section

	def new
		@lesson = Lesson.new
	end

	def create
		@lesson = current_section.lessons.create(lesson_params)
		redirect_to instructor_course_path(current_section.course)
	end

	private

	def require_authorized_for_current_section
		if current_section.course.user != current_user
      		return render plain: 'Unauthorized', status: :unauthorized
    	end
	end

	helper_method :current_section
	def current_section
		@current_section ||= Section.find(params[:section_id])
	end

	def lesson_params
		params.require(:lesson).permit(:title, :subtitle)
	end

end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
	def new
		@course = Course.find(params[:course_id])
		@section = Section.new()
	end

	def create
		@course = Course.find(params[:course_id])
		@section = @course.sections.create(section_params)
		redirect_to instructor_course_path(@course)
	end

	private

	def section_params
		params.require(:section).permit(:title)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/index.html.erb
<br />
<div class="container-offset">
	<div class="basic-box">
	  <h1 class="text-center">Learn something today</h1>
	  <hr />

	  <% @courses.each do |course| %>
	    <h2 class="text-center"><%= link_to course.title, course_path(course) %></h2>
	    <br/>
	    <div class="row">
		    <div class="col-sm-8 col-12">
		      <%= course.description %>
		    </div>
		    <div class="col-sm-4 col-12 text-center">
		      <%= link_to 'Go to course', course_path(course), class: 'btn btn-primary btn-large' %>
		    </div>
	    </div>
	    <div class="clr"></div>
	    <hr />
	    <br />
	    <br />
	  <% end %>
	</div>
</div>

app/views/courses/show.html.erb
<br />
<div class="container-offset">
	<div class="basic-box text-center">
		<h1><%= @course.title %></h1>

		<div>
			<h2><%= number_to_currency @course.cost %></h2>
		</div>

		<% if current_user && current_user == @course.user %>
			<%= link_to 'Administrator', instructor_course_path(@course), class: 'btn btn-danger btn-large'%>
		<% end %>

		<div>
			<%= @course.description %>
		</div>

	</div>
</div>

app/views/instructor/courses/new.html.erb
<br/>

<div class="container-offset basic-box">
	<h1>Add a new course</h1>
	<%= simple_form_for @course, url: instructor_courses_path do |f| %>
    	<%= f.input :title %>
    	<%= f.input :description %>
    	<%= f.input :cost %>
    	<br />
    	<%= f.submit "Create", class: 'btn btn-primary' %>
    	<br />
  	<% end %>
  	<br />
</div>

app/views/instructor/courses/show.html.erb
<br/>

<div class="container-offset basic-box">
	<h1 class="text-center"><%= @course.title %></h1>
	<div class="text-center">
		<h2><%= link_to 'Student view', course_path(@course)%></h2>
		<div class='clr'/>
  	</div>
  	<br />

  	<h2 class="text-center">Sections</h2>
  	<hr />
  	<% @course.sections.each do |section| %>
  		<u><h3><%= section.title %></h3></u>
      <% section.lessons.each do |lesson| %>
        <h4><%= lesson.title %></h4>
        <p><%= lesson.subtitle %></p>
      <% end %>
      <%= link_to 'New lesson', new_instructor_section_lesson_path(section)%>
  		<hr />

  	<% end %>

    <br/>

    <h2><%= link_to 'Add a new section', new_instructor_course_section_path(@course) %></h2>
</div>

app/views/instructor/lessons/new.html.erb
<br />

<div class="container-offset basic-box">
	<h1>Add a new lesson</h1>
	<%= simple_form_for @lesson, url: instructor_section_lessons_path(current_section) do |f| %>
    	<%= f.input :title %>
    	<%= f.input :subtitle %>
    	<br />
    	<%= f.submit "Create", class: 'btn btn-primary' %>
    	<br />
  	<% end %>
  	<br />
</div>

app/views/instructor/sections/new.html.erb
<br/>

<div class="container-offset basic-box">
  	<h1>Add a new section</h1>
  	<%= simple_form_for @section, url: instructor_course_sections_path(@course) do |f| %>
    	<%= f.input :title %>
    	<br />
    	<%= f.submit "Add a section", class: 'btn btn-primary' %>
    	<br />
    	<br />
  	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flixter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'Flixster', root_path, class: 'navbar-brand'%>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item active">
              <%= link_to 'Teach a class', new_instructor_course_path, class: 'nav-link' %>
            </li>
            <li class="nav-item active">
              <%= link_to 'See courses', courses_path, class: 'nav-link' %>
            </li>
          </ul>

          <%if user_signed_in? %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            <%= link_to 'Your profile', '#', class: 'nav-link' %>
          <%else%>
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
          <%end%>

        </div>
      </nav>

      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert basic-box"><%= alert %></p>
      <% end %>
    
    <!--Stuff in the actual page-->
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<!--Here's the hero-->
<div class="hero">
	<br /><br /><br /><br /><br /><br /><br /><br /><br />
	<div class="frosty">
		<h1 class="offset-1">Learn from the best!</h1>
		<h2 class="offset-1">We have the teachers you're looking for</h2>
		<%= link_to 'Learn More', '#', class: 'btn btn-success' %>
	</div>
</div>

<!--Here's the rest of our splash page-->

<br /> <br />

<div class="row text-center">
  <div class="basic-box col-12 col-sm">
    <h3>Amazing Courses</h3>
    <br />
    <p>Choose from any number of courses to study with amazing teachers </p>
  </div>

  <div class="basic-box col-12 col-sm">
    <h3>Learn At Your Own Pace</h3>
    <br />
    <p>Enroll and access a archive of lessons</p>
  </div>

  <div class="basic-box col-12 col-sm">
    <h3>Join Our Community</h3>
    <br />
    <p>Learn with a community of like-minded individuals</p>
  </div>
</div>